unique_ids:
  assets:
    standard-page.html: MGGRPHZLATDWZ7EFBTSIIUIXTG65GROX
    theme.css: 7CAKN3YXD55J6JWO27VITRIKTQI7TI5U
  forms:
    Form1: XICRKHATOGHTCLYRQXBKTYCL2DSPYCJH
  modules: {}
  scripts: {}
  server_modules: {}
