unique_ids:
  assets:
    standard-page.html: HSB6CBOUIFIDTLVLNURAAVUEEYLOVNUD
    theme.css: YQN2TIE7DFBFFRPEO5LZ26ZIHLO73TX2
  forms:
    Form1: CTQCKOCF75PGF2GZ27HNHWZDDK6NU4MI
  modules: {}
  scripts: {}
  server_modules: {}
