unique_ids:
  assets:
    standard-page.html: HSB6CBOUIFIDTLVLNURAAVUEEYLOVNUD
    theme.css: YQN2TIE7DFBFFRPEO5LZ26ZIHLO73TX2
  forms:
    AdminForm: 3WDLJ3IRZIOKYPOZH3HWZVC2TKQ55JE2
    Form1: CTQCKOCF75PGF2GZ27HNHWZDDK6NU4MI
  modules:
    EventCard: FDY3HDGQSC2UQWBEQ7BO4CNQ227BBBDR
  scripts: {}
  server_modules:
    admin_tools: L5OAIAIDHPDE3UQCX767ZPMDHSRTUFRU
    ai_service: 2ZXNTBY4EGECRSPRDSNYI7PWSA4JSS72
    api_helpers: DFBI4CS5ZTOBRPHVG4FTUL57V6TTGYBQ
    api_tests: I6FH2KNACRK5ODOPKXXCXYQPODUYEAPT
    background_tasks: W7ZJ7NQS2A2TWZI72XJIQSSO6E5FETAI
    config: ILATI4GU4VUTKRBT6ITVHOESZNMX5TRP
    data_processor: QZHYLUDWJ6JX6NYDTIR2HUNDC5VXEC7W
    firecrawl_diagnostics: 424SETKYBFPFAACZENE3B6TSFCIEAOAH
    scraper_direct: ATG5SX46U2QXML36CVBRQUIZHJ2JC7VP
    scraper_service: 6R7EMDVIDGTH4Y7JFZMSZCSYS4FK7QBG
    setup_schema: LC6RLPHQZV2YWHP42HE4TJ3XFA6Y6TM4
    test_data: 3SPYAFX54LAWFJARGVDZBQ6RNHK7OZKQ
    weather_service: FDCXO36LIUKD4HKBMZSSCCOEBPZB5CV6
